server:
  port: 8082

spring:
  application:
    name: service-consumer
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        service-name: ${spring.application.name}
#        register: false   # 关键：禁止注册自身
#        enabled: false    # 可选：完全禁用服务发现功能
      config:
        enabled: false  # 关键：关闭配置中心

feign:
  client:
    config:
      default:  # 全局配置
        connectTimeout: 5000  # 连接超时（毫秒）
        readTimeout: 5000     # 读取超时